name: Benchmarks

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.julia-version == 'nightly' }}
    strategy:
      matrix:
        julia-version: ['1']
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@latest
      - name: Run Turing benchmarks
        run: |
          bash -c "
          cd benchmarks && julia run-benchmarks.jl
          # TODO: Send to BenchmarkReports?
          "
      - name: Upload benchmark results to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: benchmark-results
          path: benchmarks/results/results.json
