name: CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.julia-version == 'nightly' }}
    strategy:
      matrix:
        julia-version: ['1']
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@latest
      - name: Run Turing benchmarks
        run: |
          bash -c '
          cd benchmarks-new
          julia -e "import Pkg; Pkg.instantiate()"
          julia run-benchmarks.jl
          # TODO: Send to BenchmarkReports?
          echo "Printing results/results.json:" && cat results/results.json
          '
                
